### ISSUE TITLE
Debug markers

### ISSUE THREAD

**Issue by kvark** [gfx-rs/d3d12-rs#27]
Apparently, D3D12 debug markers are supposed to be set using PIX (!) runtime - https://devblogs.microsoft.com/pix/winpixeventruntime/

I found this code in RenderDoc that would allow us to avoid going through PIX runtime:
https://github.com/baldurk/renderdoc/pull/1615/files

**Comment by curldivergence** [comment]
Hello! Actually, there is no need to pull PIX stuff into this library - I've made pixwrapper crate some time ago (it's available on crates.io) for that exact purpose, I'm using it in my own DX12 bindings library. Hope this helps :)
