### ISSUE TITLE
WeakPtr should work like ComPtr and release on drop

### ISSUE THREAD

**Issue by Ciantic** [gfx-rs/d3d12-rs#31]
I think this is a bug, or feature I don't quiet understand.

WeakPtr doesn't call `Release` on drop. It should be the default behavior of `ComPtr`, see e.g. [this implementation](https://github.com/retep998/wio-rs/blob/9bf021178b2d02485f1bd35e6cff41bf52d4a9a2/src/com.rs#L119-L125).

Also I checked, almost all of the resources should use that version of ComPtr, it's exactly same as in C++ side ComPtr, for instance resources such as:

```C++
    ComPtr<IDXGISwapChain3> m_swapChain;
    ComPtr<ID3D12Device> m_device;
    ComPtr<ID3D12Resource> m_renderTargets[FrameCount];
    ComPtr<ID3D12CommandAllocator> m_commandAllocator;
    ComPtr<ID3D12CommandQueue> m_commandQueue;
    ComPtr<ID3D12RootSignature> m_rootSignature;
    ComPtr<ID3D12DescriptorHeap> m_rtvHeap;
    ComPtr<ID3D12PipelineState> m_pipelineState;
    ComPtr<ID3D12GraphicsCommandList> m_commandList;
```
(Copied from [MS example](https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12HelloWorld/src/HelloTriangle/D3D12HelloTriangle.h))

If we use the current implementation for WeakPtr it doesn't call Release unless you manually call it. It's in my opinion very error prone.

Only reason you want to leak resources for a bit, is if you don't know if the resource is used by the GPU. But that is solved by [fencing/waiting](https://github.com/microsoft/DirectX-Graphics-Samples/blob/58b6bb18b928d79e5bd4e5ba53b274bdf6eb39e5/Samples/Desktop/D3D12HelloWorld/src/HelloTriangle/D3D12HelloTriangle.cpp#L277-L279) and it's probably already done at higher level.

There might be reasons to leak resources, but it should not be default.

**Comment by msiglreith** [comment]
The library was mostly designed to work with gfx-hal's dx12 backend. Initially started with wio's ComPtr but went with some more thin layer (WeakPtr). Motivated by points like Copy vs Clone semantics (Acquire/Release) as we needed to store references to resources internally, gfx-hal has explicit destruction semantics anyway so having `Drop` was not that important. Also, handling errors on resource creation was a bit easier IIRC. Overall `WeakPtr` was intended to be a very thin layer, which is not owning the resource.
Given the ongoing advances in the windows ecosystem things may shift but I haven't followed too closely tbh

**Comment by Ciantic** [comment]
Thanks. I'll close this if it's intentional. 

This practically means that some higher level library calls `destroy()` *manually* on all of these:

```rust

	pub type CommandAllocator = WeakPtr<d3d12::ID3D12CommandAllocator>;
	pub type CommandSignature = WeakPtr<d3d12::ID3D12CommandSignature>;
	pub type CommandList = WeakPtr<d3d12::ID3D12CommandList>;
	pub type GraphicsCommandList = WeakPtr<d3d12::ID3D12GraphicsCommandList>;
	pub type Debug = WeakPtr<d3d12sdklayers::ID3D12Debug>;
	pub type DescriptorHeap = WeakPtr<d3d12::ID3D12DescriptorHeap>;
	pub type RootSignature = WeakPtr<d3d12::ID3D12RootSignature>;
	pub type Device = WeakPtr<d3d12::ID3D12Device>;
	pub type Adapter1 = WeakPtr<dxgi::IDXGIAdapter1>;
	pub type Factory2 = WeakPtr<dxgi1_2::IDXGIFactory2>;
	pub type Factory4 = WeakPtr<dxgi1_4::IDXGIFactory4>;
	pub type InfoQueue = WeakPtr<dxgidebug::IDXGIInfoQueue>;
	pub type SwapChain = WeakPtr<dxgi::IDXGISwapChain>;
	pub type SwapChain1 = WeakPtr<dxgi1_2::IDXGISwapChain1>;
	pub type SwapChain3 = WeakPtr<dxgi1_4::IDXGISwapChain3>;
	pub type Heap = WeakPtr<d3d12::ID3D12Heap>;
	pub type Blob = WeakPtr<d3dcommon::ID3DBlob>;
	pub type Error = WeakPtr<d3dcommon::ID3DBlob>;
	pub type PipelineState = WeakPtr<d3d12::ID3D12PipelineState>;
	pub type QueryHeap = WeakPtr<d3d12::ID3D12QueryHeap>;
	pub type CommandQueue = WeakPtr<d3d12::ID3D12CommandQueue>;
	pub type Resource = WeakPtr<d3d12::ID3D12Resource>;
	pub type Fence = WeakPtr<d3d12::ID3D12Fence>;
```

**Comment by kvark** [comment]
Perhaps this should be a compile-time feature?

**Comment by Ciantic** [comment]
I'm fine with current behavior, even though I don't understand the underlying complexities. 
I think it's not possible to implement this as compile-time feature on d3d12 crate at least because gfx expects this behavior?

I checked the examples in `gfx` crate e.g. Quad ([creation](https://github.com/gfx-rs/gfx/blob/4b63f30807204b22f1ba52bb3356e69e19fb896a/examples/quad/main.rs#L174-L203), [drop](https://github.com/gfx-rs/gfx/blob/4b63f30807204b22f1ba52bb3356e69e19fb896a/examples/quad/main.rs#L982-L1034)), it does the destructuring manually. 

(Indeed there might be some advantage on lower level libraries for this manual dropping, such as some implementations might want to destructure in different thread. After all that gfx crate is still lowe level crate.)

**Comment by kvark** [comment]
> I think it's not possible to implement this as compile-time feature on d3d12 crate at least because gfx expects this behavior?

If `weak-ptr` is a feature here, gfx-rs would just enable it.

**Comment by Ciantic** [comment]
Yes, that is an option. However more I studied how gfx uses this library, I think d3d12-rs library is not that useful. It wraps only few of the methods and GFX just calls the Directx API directly in many occasions.

Also as a wrapper d3d12 library is not good to be honest. It exposes the HRESULT to higher level, you need to provide uninitialized ptr to the methods, and using it feels like using the APIs directly. I redid my example with pure winapi bindings, and the code lenght is about the same because HRESULT is not handled, etc.

If this library aims to be general puropse wrapper, it should take this approach: https://github.com/LNSEAB/dxplr/blob/master/examples/d3d12/triangle/main.rs

And I'm personally unsure is all that work really useful, compared to using just the winapi bindings directly. Many times the GFX library just resorts to using winapi bindings directly because the implementation in d3d12-rs library is not suitable for it's needs.

Personally I would either expand this library radically (to make it also general purpose wrapper) or deprecate it entirely from the gfx stack.

However currently we must live with this library as some parts of GFX depends on this, so I continue my small PR on composition with d3d12-rs for the time being.

**Comment by cwfitzgerald** [comment]
This was changed #45
